kind: Service
apiVersion: v1
metadata:
  name: fe-pipeline
  namespace: default
spec:
  selector:
    app: fe-pipeline
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-pipeline
  namespace: default
  labels:
    app: fe-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-pipeline
  template:
    metadata:
      labels:
        app: fe-pipeline
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
      - name: fe-pipeline
        image: harbor.hft.jajabjbj.top:30088/hft/fe-pipeline:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  generation: 1
  name: fe-pipeline
spec:
  rules:
  - host: fe-pipeline.hft.jajabjbj.top
    http:
      paths:
      - backend:
          serviceName: fe-pipeline
          servicePort: 3000
